### ISSUE TITLE
error when adding description to Individual node

### ISSUE THREAD

**Issue by valeriosantarelli** [danielepantaleone/eddy#32]
When a description is added to an individual node and the project is saved, the following error is produced:

Traceback (most recent call last):
  File "/Users/jenkins/Desktop/eddy/eddy/ui/session.py", line 1525, in doSave
  File "/Users/jenkins/Desktop/eddy/eddy/core/exporters/graphol.py", line 545, in run
  File "/Users/jenkins/Desktop/eddy/eddy/core/exporters/graphol.py", line 508, in createPredicatesMeta
KeyError: <Item.IndividualNode: 65541>

**Comment by danielepantaleone** [comment]
This must be a funny one. I'll have a look.
